---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Informationen zu den neuesten Änderungen an den Funktionen und Datendiensten, die Teil der lokalen NetApp Console-Bereitstellung sind. 
---
= Jüngste Änderungen an der lokalen Bereitstellung der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informationen zu den neuesten Änderungen an den Funktionen und Datendiensten, die Teil der lokalen NetApp Console-Bereitstellung sind.



[[21-september-2026]]
== 21. September 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.09*: Diese Version enthält Trident Protect 26.09.
* *Cluster- und Namespace-spezifische rollenbasierte Zugriffskontrolle*: Während der Kubernetes-Clustererkennung lässt sich der Zugriff auf Ressourcen steuern, indem ein Projekt oder ein Ordner ausgewählt wird, das bzw. der dem neuen Cluster zugeordnet wird. Auch können spezifische Namespaces für die Zugriffskontrolle registriert werden. Dadurch wird eine granularere Zugriffskontrolle auf Cluster- oder Namespace-Ebene ermöglicht.
* *Dateien und Ordner wiederherstellen*: Es ist jetzt möglich, bestimmte Dateien und Ordner aus Kubernetes VM-basierten Anwendungssicherungen wiederherzustellen oder herunterzuladen.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Informationen zum Schutz von Kubernetes Workloads mit NetApp Backup and Recovery"].



[[16-september-2026]]
== 16. September 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Allgemeine NetApp Backup and Recovery-Verbesserung

In dieser Version führen KVM-, Hyper-V- und VMware-Workloads die folgende Verbesserung ein:

*Auswahl der Anmeldeinformationen bei der VM-Host-Erkennung*: Bei der Erkennung eines KVM-, Hyper-V- oder VMware-Hosts können jetzt Anmeldeinformationen verwendet werden, die bereits zu Backup and Recovery hinzugefügt wurden.



==== Hyper-V Workload-Verbesserung

In dieser Version wird für Hyper-V Workloads die folgende Verbesserung eingeführt:

*Datenträgerübergreifender Schutz für VMs*: Bei CIFS-Konfigurationen unterstützt NetApp Backup and Recovery jetzt den Schutz aller an jede VM in einer Datensicherungsstrategie angeschlossenen Datenträger. Dies umfasst Dateien, die über mehrere ONTAP Volumes oder ONTAP Speichersysteme verteilt sind (datenträgerübergreifende Datenträger), sowie Dateien, die sich an einem einzigen Speicherort befinden.

Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Informationen zum Schutz von Hyper-V Workloads mit NetApp Backup and Recovery"].



==== ONTAP Volumes Workloads-Verbesserung

In dieser Version wird für ONTAP Volumes Workloads die folgende Vorschau-Verbesserung eingeführt:

*Täglicher Bericht zum Datentransfer bei Backups*: NetApp Backup and Recovery für Volumes enthält jetzt unter der Registerkarte „Berichte“ einen täglichen Bericht zum Datentransfer bei Backups, der Einblick in die täglichen Backup- und Replikations-Datentransfers in Ihrer Umgebung bietet. Der Bericht kann für das gesamte Konto oder für ausgewählte Speichersysteme erstellt, nach Datumsbereich und Datensicherungsstrategie gefiltert und als CSV heruntergeladen werden.

Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Informationen zum ONTAP Volumeschutz mit NetApp Backup und Recovery"].



[[17-august-2026]]
== 17. August 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Hyper-V-Workload-Verbesserungen

In dieser Version wird für Hyper-V Workloads die folgende Verbesserung eingeführt:

*Objektspeichersicherung an alternativem Speicherort wiederherstellen*: Es ist jetzt möglich, Hyper-V-VMs, Dateien und Ordner aus dem Objektspeicher an einem alternativen Speicherort wiederherzustellen.

Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Informationen zum Schutz von Hyper-V Workloads mit NetApp Backup and Recovery"].



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.08*: Diese Version enthält Trident Protect 26.08.
* *Backup-Wiederholungsversuche*: Backup-Wiederholungsversuche können jetzt aktiviert und die Anzahl der Wiederholungsversuche sowie die Intervalle zwischen den Wiederholungsversuchen als erweiterte Einstellungen in Kubernetes-Schutzrichtlinien konfiguriert werden.
* *Teilweise erfolgreiche Sicherung*: Es besteht jetzt die Möglichkeit, in den Kubernetes-Schutzrichtlinien erweiterte Einstellungen zu konfigurieren, damit die Sicherung auch bei Ausfall einzelner Ressourcen fortgesetzt wird und Sicherungsaufträge als teilweise erfolgreich abgeschlossen werden können. Dadurch ist die Wiederherstellung gesicherter Ressourcen möglich, selbst wenn während des Sicherungsvorgangs einige Ressourcen ausfallen.
* *Absturzkonsistente und VM-konsistente Backups*: Der Backup and Recovery Dienst für NetApp Console unterstützt jetzt die Konfiguration von Schutzrichtlinien, die absturzkonsistente oder VM-konsistente Backups oder Snapshots erstellen. Es besteht zudem die Möglichkeit, anzupassen, wie VM-Einfrierungen während des Schutzvorgangs durchgeführt werden.
* *Wiederverbindung des Kubernetes-Clusters bei Änderung der Console-Agent-IP-Adresse*: Der Backup- und Wiederherstellungsdienst für NetApp Console ermöglicht jetzt die erneute Verbindung eines Clusters mit seinem Console-Agenten, wenn sich die IP-Adresse des Agenten ändert.
* *Cluster auf neuen Console Agent migrieren*: Der Backup and Recovery Dienst für NetApp Console ermöglicht jetzt die Migration eines Clusters auf einen neuen Console Agent, falls der ursprüngliche Agent ausfällt oder gelöscht wird, wodurch ein unterbrechungsfreier Anwendungsschutz sichergestellt wird.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Informationen zum Schutz von Kubernetes Workloads mit NetApp Backup and Recovery"].



==== Erweiterung der Oracle Database Workloads

In dieser Version werden die folgenden Verbesserungen für Oracle Database workloads eingeführt:

* *Wiederherstellung von Pluggable Databases (PDBs)*: Es ist jetzt möglich, einzelne Pluggable Databases (PDBs) und PDB-Tablespaces wiederherzustellen, einschließlich zeitpunktgenauer Wiederherstellung.
* *Pluggable Database (PDB) Klonen*: Es ist jetzt möglich, eine einzelne PDB in eine bestehende Ziel-Containerdatenbank (CDB) zu klonen und optional PDBs auszuschließen, wenn eine komplette Containerdatenbank geklont wird.


Weitere Informationen zum Schutz von Oracle Database-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Informationen zum Schutz von Oracle Database Workloads mit NetApp Backup and Recovery"].



[[10-august-2026]]
== 10. August 2026



[[netapp-console-local-deployment]]
=== NetApp Console lokale Bereitstellung



==== Einführung der lokalen NetApp Console-Bereitstellung

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Lokale Bereitstellung der NetApp Console kennenlernen"].

https://docs.netapp.com/us-en/console-local/console-differences.html["Die Unterschiede zwischen der lokalen Bereitstellung der NetApp Console und NetApp Console SaaS und dem privaten Modus"].



[[backup-and-recovery]]
=== Backup and Recovery



==== Allgemeine NetApp Backup and Recovery-Verbesserungen

* *Unterstützung für die lokale Bereitstellung der NetApp Console*: Diese Version von NetApp Backup and Recovery unterstützt die lokale Bereitstellung der NetApp Console im Vorschaustatus.
* *90 Tage Aufbewahrung von Aufträgen*: Backup and Recovery speichert Auftragsinformationen jetzt 90 Tage lang im Job Monitor.




==== VMware Workload-Verbesserungen

In dieser Version führt VMware workloads die folgenden Verbesserungen ein:

* *Unterstützung für die Wiederherstellung an einem alternativen Speicherort für SAN-VMs*: Es ist jetzt möglich, SAN-basierte VM-Backups an einem alternativen Speicherort wiederherzustellen.
* *Unterstützung für das Löschen mehrerer Backups*: Es ist jetzt möglich, mehrere Backups gleichzeitig zu löschen.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Vorschauunterstützung für isolierte Ressourcen*: Wenn NetApp Backup and Recovery in der lokalen NetApp Console-Bereitstellung ausgeführt wird, können isolierte Kubernetes-Ressourcen erkannt, geschützt und wiederhergestellt werden. Diese Funktion befindet sich in dieser Version in der Vorschau.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



==== ONTAP Volumes Workloads-Verbesserungen

In dieser Version wurden für ONTAP Volumes Workloads die folgenden Verbesserungen eingeführt:

* *Wiederherstellungsaufträge gegenüber Backups priorisieren*: Es besteht jetzt die Möglichkeit, Wiederherstellungsaufträge gegenüber Backup-Aufträgen zu priorisieren, wenn VMs oder Dateien wiederhergestellt werden.
* *ONTAP Systeme und Volumes ohne Backup and Recovery Aktivierung entdecken*: Es ist jetzt möglich, Systeme und Volumes zu entdecken, ohne Backup and Recovery zu aktivieren.


Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Überblick über den Schutz von ONTAP Volumes Workloads"].



[[13-july-2026]]
== 13. Juli 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Erweiterte Unterstützung mehrerer Buckets für alle Workloads

NetApp Backup and Recovery unterstützt jetzt den Schutz von Workloads innerhalb eines Systems mit bis zu 100 Buckets bei verschiedenen Cloud-Anbietern. ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System zu unterstützen.

Weitere Informationen zu NetApp Backup und Recovery finden sich unter  https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Informationen zu NetApp Backup and Recovery"].
