---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Informationen zu den neuesten Änderungen an den Funktionen und Datendiensten, die Teil der lokalen NetApp Console-Bereitstellung sind. 
---
= Jüngste Änderungen an der lokalen Bereitstellung der NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Informationen zu den neuesten Änderungen an den Funktionen und Datendiensten, die Teil der lokalen NetApp Console-Bereitstellung sind.



[[10-august-2026]]
== 10. August 2026



[[netapp-console-local-deployment]]
=== NetApp Console lokale Bereitstellung



==== Einführung der lokalen NetApp Console-Bereitstellung

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Lokale Bereitstellung der NetApp Console kennenlernen"].



[[backup-and-recovery]]
=== Backup and Recovery



==== Allgemeine NetApp Backup and Recovery-Verbesserungen

* *Unterstützung für die lokale Bereitstellung der NetApp Console*: Diese Version von NetApp Backup and Recovery unterstützt die lokale Bereitstellung der NetApp Console im Vorschaustatus.
* *90 Tage Aufbewahrung von Aufträgen*: Backup and Recovery speichert Auftragsinformationen jetzt 90 Tage lang im Job Monitor.




==== VMware Workload-Verbesserungen

In dieser Version führt VMware workloads die folgenden Verbesserungen ein:

* *Unterstützung für die Wiederherstellung an einem alternativen Speicherort für SAN-VMs*: Es ist jetzt möglich, SAN-basierte VM-Backups an einem alternativen Speicherort wiederherzustellen.
* *Unterstützung für das Löschen mehrerer Backups*: Es ist jetzt möglich, mehrere Backups gleichzeitig zu löschen.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Vorschauunterstützung für isolierte Ressourcen*: Wenn NetApp Backup and Recovery in der lokalen NetApp Console-Bereitstellung ausgeführt wird, können isolierte Kubernetes-Ressourcen erkannt, geschützt und wiederhergestellt werden. Diese Funktion befindet sich in dieser Version in der Vorschau.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



==== ONTAP Volumes Workloads-Verbesserungen

In dieser Version wurden für ONTAP Volumes Workloads die folgenden Verbesserungen eingeführt:

* *Wiederherstellungsaufträge gegenüber Backups priorisieren*: Es besteht jetzt die Möglichkeit, Wiederherstellungsaufträge gegenüber Backup-Aufträgen zu priorisieren, wenn VMs oder Dateien wiederhergestellt werden.
* *ONTAP Systeme und Volumes ohne Backup and Recovery Aktivierung entdecken*: Es ist jetzt möglich, Systeme und Volumes zu entdecken, ohne Backup and Recovery zu aktivieren.


Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Überblick über den Schutz von ONTAP Volumes Workloads"].



[[13-july-2026]]
== 13. Juli 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Erweiterte Unterstützung mehrerer Buckets für alle Workloads

NetApp Backup and Recovery unterstützt jetzt den Schutz von Workloads innerhalb eines Systems mit bis zu 100 Buckets bei verschiedenen Cloud-Anbietern. ONTAP 9.19.1 oder höher ist erforderlich, um mehr als 6 Buckets pro System zu unterstützen.

Weitere Informationen zu NetApp Backup und Recovery finden sich unter  https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Informationen zu NetApp Backup and Recovery"].



[[15-june-2026]]
== 15. Juni 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Kubernetes-Workloads-Erweiterungen

In dieser Version werden für Kubernetes-Workloads die folgenden Verbesserungen eingeführt:

* *Trident Protect 26.06*: Diese Version enthält Trident Protect 26.06.
* *Anwendungserstellung bei Wiederherstellung überspringen*: Die automatische Erstellung benutzerdefinierter Anwendungsressourcenobjekte kann während Wiederherstellungsvorgängen nun übersprungen werden. Dies reduziert unnötige Einträge im Anwendungsinventar.
* *Wiederherstellung persistenter Volume Claims in VMs*: Bei der Wiederherstellung von VM-basierten Anwendungen ist es jetzt möglich, einzelne persistente Volume Claims wiederherzustellen, ohne die gesamte virtuelle Maschine wiederherstellen zu müssen, was die Wiederherstellung beschleunigt, wenn bestimmte Festplatten oder Volumes von Beschädigungen oder Datenverlust betroffen sind.
* *Verbesserungen im Jobmonitor*: Die Überwachung von Jobs bietet jetzt eine verbesserte Transparenz bei Kubernetes-Schutzjobs. Detaillierte Statusinformationen zu Jobs und Subjobs sowie der jeweils verwendete Zielspeicher sind einsehbar.


Weitere Informationen zum Schutz von Kubernetes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Übersicht zum Schutz von Kubernetes-Workloads"].



[[08-june-2026]]
== 08. Juni 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== ONTAP Volumes Workloads-Verbesserungen

In dieser Version führt ONTAP Volumes-Workloads die folgende Verbesserung ein:

*Unterstützung für S3-kompatiblen Cloud-Speicher*: NetApp Backup and Recovery für Volumes-Workloads unterstützt jetzt das Sichern in S3-kompatiblen Cloud-Speicher.

Weitere Informationen zum Schutz von ONTAP Volumes-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Überblick über den Schutz von ONTAP Volumes Workloads"].



==== Hyper-V-Workload-Verbesserungen

In dieser Version werden für Hyper-V-Workloads die folgenden Verbesserungen eingeführt:

* *Wiederherstellen von Dateien und Ordnern in einer Gast-VM – Verbesserungen*: Sie können jetzt Dateien und Ordner aus einem Snapshot auf primärem oder sekundärem Speicher in einer Gast-Windows-VM wiederherstellen. Diese Funktion wird nun für CIFS- und SAN-VMs unterstützt.
* *Schutzgruppen verwenden jetzt die Zeitzone des Hyper-V-Hosts*: Schutzgruppen verwenden nun die Zeitzone des Hyper-V-Hosts. Schutzgruppen, die vor der Einführung der Host-Zeitzonenplanung erstellt wurden, verwenden weiterhin ihre zuvor konfigurierte Zeit (typischerweise UTC). Damit diese Schutzgruppen die Zeitzone des Hyper-V-Hosts verwenden, ist es erforderlich, die Zeitpläne neu zu erstellen. Weitere Informationen sind unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für Hyper-V Workloads"] verfügbar.


Weitere Informationen zum Schutz von Hyper-V-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Übersicht zum Schutz von Hyper-V-Workloads"].



==== VMware Workload-Verbesserungen

In dieser Version führt VMware Workloads die folgende Verbesserung ein:

* *Schutzgruppen verwenden jetzt die Zeitzonenplanung des Hosts*: Schutzgruppen verwenden nun die Zeitzone des VMware vCenter Servers. Schutzgruppen, die vor der Einführung der Host-Zeitzonenplanung erstellt wurden, laufen weiterhin in ihrer zuvor konfigurierten Zeitzone (typischerweise UTC). Um die vCenter-Zeitzone zu nutzen, ist es erforderlich, die Zeitpläne neu zu erstellen. Weitere Informationen sind unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Erstellen und Verwalten von Schutzgruppen für VMware Workloads"] verfügbar.


Weitere Informationen zum Schutz von VMware-Workloads finden Sie unter  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Überblick über den Schutz von VMware-Workloads"].
